add elsatic release job

diff --git a/stack/elastic/Makefile b/stack/elastic/Makefile
--- a/stack/elastic/Makefile
+++ b/stack/elastic/Makefile
@@ -8,7 +8,7 @@ export AWS_REGION=$(TEST_REGION)
 
 # stack name can be generated by CI
 ifndef TEST_STACK_NAME
-override TEST_STACK_NAME = elastic-event-store-integ-test-1
+override TEST_STACK_NAME = elastic-event-store-integ-test-2
 endif
 
 # Event store name
@@ -18,20 +18,22 @@ TEST_PARAMS = Name=$(TEST_STACK_NAME)
 ELASTIC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
 
 # elastic related build and test of should ignore parent workspace
-# elastic%: export GOWORK=on
+# elastic%: export GOWORK=off
 
 elastic/stackname:
 	cd $(ELASTIC_DIR); \
 	echo $(TEST_STACK_NAME)
 
-# it fails at the moment, sam validate does not support "LanguageExpression" transform
+# it fails at the moment; sam validate does not support "LanguageExpression" transform
 elastic/validate:
 	cd $(ELASTIC_DIR); \
 	sam validate
 
 elastic/build:
 	cd $(ELASTIC_DIR); \
-	go get -u github.com/ln80/event-store; \
+	v="`go list -m -f '{{ .Version }}' github.com/ln80/event-store`"; \
+	if [  "$v" == "" ]; then echo "module version not found" ; exit 2; fi; \
+	echo "Go module version: $$v"; \
 	sam build
 
 elastic/package:
@@ -40,7 +42,13 @@ elastic/package:
 
 elastic/publish:
 	cd $(ELASTIC_DIR); \
-	sam publish --template packaged.yaml --region $(AWS_REGION)
+	if [  "$v" == "" ]; \
+	then \
+		sam publish --template packaged.yaml  --fail-on-same-version   --region $(AWS_REGION); \
+	else \
+		sam publish --template packaged.yaml  --semantic-version $(v) --fail-on-same-version  --region $(AWS_REGION); \
+	fi
+
 
 elastic/deploy:
 	cd $(ELASTIC_DIR); \
@@ -56,7 +64,7 @@ elastic/deploy:
 
 
 
-elastic/unit-test/run: export GOWORK=
+# elastic/unit-test/run: export GOWORK=
 elastic/unit-test/run: 
 	cd $(ELASTIC_DIR); \
 	echo GOWORK=$(GOWORK); \
@@ -75,7 +83,7 @@ elastic/integ-test/deploy:
 		--config-env $(TEST_ENV) \
 		--capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
 		--region $(TEST_REGION) \
-		--resolve-s3 \
+		--resolve-s3
 
 elastic/integ-test/clear:
 	cd $(ELASTIC_DIR); \
