setup elastic ci/cd (#5)

diff --git a/stack/elastic/Makefile b/stack/elastic/Makefile
--- a/stack/elastic/Makefile
+++ b/stack/elastic/Makefile
@@ -4,32 +4,36 @@
 TEST_ENV = test
 TEST_REGION = eu-west-1
 
+export AWS_REGION=$(TEST_REGION)
+
 # stack name can be generated by CI
 ifndef TEST_STACK_NAME
-override TEST_STACK_NAME = elastic-event-store-integ-test-1
+override TEST_STACK_NAME = elastic-event-store-integ-test-2
 endif
 
 # Event store name
 TEST_PARAMS = Name=$(TEST_STACK_NAME)
 
-# mainly used by integ test runner
-export AWS_REGION=$(TEST_REGION)
-
 
 ELASTIC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
+
+# elastic related build and test of should ignore parent workspace
+elastic%: export GOWORK=off
 
 elastic/stackname:
 	cd $(ELASTIC_DIR); \
 	echo $(TEST_STACK_NAME)
 
-# it fails at the moment, sam validate does not support "LanguageExpression" transform
 elastic/validate:
 	cd $(ELASTIC_DIR); \
 	sam validate
 
 elastic/build:
 	cd $(ELASTIC_DIR); \
-	sam build
+	v="`go list -m -f '{{ .Version }}' github.com/ln80/event-store`"; \
+	# if [  "$v" == "" ]; then echo "module version not found" ; exit 2; fi; \
+	echo "Go module version: $$v"; \
+	sam build --template-file ./template.yaml
 
 elastic/package:
 	cd $(ELASTIC_DIR); \
@@ -37,19 +41,32 @@ elastic/package:
 
 elastic/publish:
 	cd $(ELASTIC_DIR); \
-	sam publish --template packaged.yaml --region $(AWS_REGION)
+	if [  "$v" == "" ]; \
+	then \
+		sam publish --template packaged.yaml  --fail-on-same-version   --region $(AWS_REGION); \
+	else \
+		sam publish --template packaged.yaml  --semantic-version $(v) --fail-on-same-version  --region $(AWS_REGION); \
+	fi
 
-elastic/deploy:
+# elastic/deploy:
+# 	cd $(ELASTIC_DIR); \
+# 	sam deploy \
+# 		--no-confirm-changeset \
+# 		--no-fail-on-empty-changeset \
+# 		--stack-name $(TEST_STACK_NAME) \
+# 		--config-env $(TEST_ENV) \
+# 		--capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
+# 		--region $(TEST_REGION) \
+# 		--s3-bucket ln80-sam-pkgs \
+# 		--parameter-overrides $(TEST_PARAMS)
+
+
+
+# elastic/unit-test/run: export GOWORK=
+elastic/unit-test/run: 
 	cd $(ELASTIC_DIR); \
-	sam deploy \
-		--no-confirm-changeset \
-		--no-fail-on-empty-changeset \
-		--stack-name $(TEST_STACK_NAME) \
-		--config-env $(TEST_ENV) \
-		--capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
-		--region $(TEST_REGION) \
-		--s3-bucket ln80-sam-pkgs \
-		--parameter-overrides $(TEST_PARAMS)
+	echo GOWORK=$(GOWORK); \
+	go test --tags=unit -race -cover -v ./...
 
 elastic/integ-test/build:
 	cd $(ELASTIC_DIR); \
@@ -64,7 +81,7 @@ elastic/integ-test/deploy:
 		--config-env $(TEST_ENV) \
 		--capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
 		--region $(TEST_REGION) \
-		--resolve-s3 \
+		--resolve-s3
 
 elastic/integ-test/clear:
 	cd $(ELASTIC_DIR); \
